package p1Pkge;

//Token Definitions

enum Token {NOT_FOUND, UPPER_CASE_IDENTIFIER, CONSTANT, COMMENT,
  COMPILER_DIRECTIVE, ASSIGNMENT_OPERATOR,
  PRE_OR_POST_UNARY_OPERATOR, STRUCTURE_OPERATOR,
  UNARY_OR_BINARY_OPERATOR,UNARY_OPERATOR, BINARY_OPERATOR,
  TERNARY_OPERATOR, COLON, LEFT_PARENTHESIS, RIGHT_PARENTHESIS,
  LEFT_BRACKET, RIGHT_BRACKET, LEFT_BRACE, RIGHT_BRACE, SEMICOLON,
  COMMA, STRING, SC_SPECIFIER, BREAK, CASE, TYPE_SPECIFIER,
  CONTINUE, DEFAULT, DO, ELSE, FOR, GOTO, IF, RETURN, SIZEOF,
  STATUS, STRUCT, SWITCH, UNION, WHILE, IDENTIFIER, FIRST, NONE,
  END_OF_FILE}


public class Lexer {

}
